version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: namaa-postgres
    environment:
      POSTGRES_DB: namaa_dev
      POSTGRES_USER: namaa
      POSTGRES_PASSWORD: namaa
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: namaa-redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
