name: namaa_app
description: Youth-centric smart savings app (prototype)
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_analytics: ^10.5.0
  http: ^1.1.0
  go_router: ^9.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Plus Jakarta Sans
  #     fonts:
  #       - asset: assets/fonts/PlusJakartaSans-Regular.ttf
  #       - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
  #         weight: 600
  assets:
    - assets/images/
    # - assets/fonts/
